package ies.quevedo.chardat.domain.enums

enum class Armaduras {
    ACOLCHADA, ANILLAS, COMPLETA, COMPLETA_DE_CUERO, COMPLETA_PESADA, COTA_DE_CUERO,
    CUERO_ENDURECIDO, CUERO_TACHONADO, DE_CAMPANA_PESADA, ESCAMAS, GABARDINA, MALLAS, PETO, PIEL,
    PIEZAS, PLACAS, SEMICOMPLETA
}