package ies.quevedo.chardat.domain.enums

enum class Armas {
    ALABARDA, ARCO_COMPUESTO, ARCO_CORTO, ARCO_LARGO, ARPON, BALLESTA, BALLESTA_DE_MANO, BALLESTA_DE_REPETICION,
    BALLESTA_PESADA, CADENA, CERBATANA, CESTUS, CIMITARRA, DAGA, DAGA_DE_PARADA, ESPADA_ANCHA,
    ESPADA_BASTARDA, ESPADA_CORTA, ESPADA_LARGA, ESTILETE, ESTOQUE, FLAGELO,
    FLORETE, FUSIL, GARFIO, GARROTE, GRAN_MARTILLO_DE_GUERRA, GUADANA, HACHA_A_DOS_MANOS, HACHA_DE_GUERRA,
    HACHA_DE_MANO, HONDA, JABALINA, LANZA, LANZA_DE_CABALLERIA, LATIGO, LAZO, MANDOBLE, MANGUAL, MARTILLO_DE_GUERRA,
    MAYAL, MAZA, MAZA_PESADA, PISTOLA, RED_DE_GLADIADOR, SABLE, TRIDENTE, VARA
}