package ies.quevedo.chardat.domain.enums

enum class Armas1H {
    ALABARDA, ARPON, CADENA, CESTUS, CIMITARRA, DAGA, DAGA_DE_PARADA, ESPADA_ANCHA,
    ESPADA_BASTARDA, ESPADA_CORTA, ESPADA_LARGA, ESTILETE, ESTOQUE, FLAGELO, FLORETE, GARFIO,
    GARROTE, GRAN_MARTILLO_DE_GUERRA, GUADANA, HACHA_A_DOS_MANOS, HACHA_DE_GUERRA, HACHA_DE_MANO,
    JABALINA, LANZA, LANZA_DE_CABALLERIA, LATIGO, LAZO, MANDOLE, MANGUAL, MARTILLO_DE_GUERRA,
    MAYAL, MAZA, MAZA_PESADA, RED_DE_GLADIADOR, SALE, TRIDENTE, VARA
}