package ies.quevedo.chardat.domain.enums

enum class Armas2H {
    ALABARDA, ARPON, ESPADA_A_DOS_MANOS, ESPADA_BASTARDA, GRAN_MARTILLO_DE_GUERRA, GUADANA,
    HACHA_A_DOS_MANOS, LANZA, LANZA_DE_CABALLERIA, MAZA_PESADA, TRIDENTE, VARA
}