package ies.quevedo.chardat.domain.enums

enum class Clase {
    GUERRERO,
    GUERRERO_ACROBATA,
    PALADIN,
    PALADIN_OSCURO,
    MAESTRO_DE_ARMAS,
    TECNICISTA,
    TAO,
    EXPLORADOR,
    SOMBRA,
    LADRON,
    ASESINO,
    HECHICERO,
    WARLOCK,
    ILUSIONISTA,
    HECHICERO_MENTALISTA,
    CONJURADOR,
    GUERRERO_CONJURADOR,
    MENTALISTA,
    GUERRERO_MENTALISTA,
    NOVEL
}